### ISSUE TITLE
CRITICAL: Invalid TIN when adding vertices

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#36] opened 2018-03-14 13:45 UTC
Invalid TIN is created after adding vertex with id=4. Edge is created between vertices 0 and 4 instead of 3 and 4.
This issue is reproducible in both implementations. Test code attached. Distance is between edge and vertex.

!!! ERROR !!! Vertex  3: x=34.00562309702486, y=160.76445998375877, z=0.0 is near to edge:        18         21 <-- (        4,        0) -->        13, distance=5.453774778801268E-15

![ss-invalid-tin](https://user-images.githubusercontent.com/7425758/37405842-0b9e69e0-2796-11e8-86da-8e6fb372399f.png)

[test.zip](https://github.com/gwlucastrig/Tinfour/files/1811298/test.zip)

**Comment by jandam** [comment] 2018-03-14 13:49
I think that this issue is leads to #35

**Comment by gwlucastrig** [comment] 2018-03-14 21:54
I can reproduce the problem and am investigating the cause.

**Comment by gwlucastrig** [comment] 2018-03-15 00:25
I'm working on this, and I'm stuck,  Do you have any ideas or suggestions?

 Referring to the image below, the following triangles are produced with areas as indicated:

      0,   1,   2,   2.587044e+00
      0,   2,   3,   1.825173e+00
      0,   3,   4,   5.542389e-14
      3,   2,   4,   1.625575e+01

Triangle 0,3,4 has a positive area, so is valid by the definitions of Tinfour.  And without it the perimeter of the TIN would not be properly convex.  But I have to agree that I don't like seeing such a nearly degenerate triangle and would prefer if it were omitted.   Right now, the only solution I can think of is to somehow adjust the position of vertex 4.  


![item36](https://user-images.githubusercontent.com/19698145/37437493-e9cd196e-27c3-11e8-9d5b-591530222b6b.png)

To perform the calculation, I used the following.  In the case of triangle 0,3,4, the area calculation actually had to roll over to extended precision arithmetic because the area was so small.
 
      Thresholds thresholds = tin.getThresholds();
      GeometricOperations geoOp = new GeometricOperations(thresholds);
      TriangleCollector.visitTriangles(tin, new Consumer<Vertex[]>() {
        @Override
        public void accept(Vertex[] vArray) {
          double area = geoOp.area(vArray[0], vArray[1], vArray[2]);
          System.out.format("    %3d, %3d, %3d,   %e%n",
                  vArray[0].getIndex(),
                  vArray[1].getIndex(),
                  vArray[2].getIndex(),
                  area);
        }
      }
      );

**Comment by gwlucastrig** [comment] 2018-03-15 09:36
This is a difficult problem.  I did some tests where I tried to replace point 3 with the closest point that would lie on the segment from vertex 4 to vertex 0.  The idea being that this would give a TIN with two perimeter edges from 4 to 3 and 3 to 0 and would eliminate the very thin triangle we were seeing.

Unfortunately,  every calculation I tried always resulted in the same coordinates as vertex 3.  Basically, numerical precision issues prevent an exact solution.  I even tried extended precision math, but got the same results.  I also tried adjusting the position of vertex 3 outward using an arbitrary small factor.  This approach eliminated triangle 0, 3,4.  But it created a new problematic triangle 0,3,1.

I wonder if there might exist an numerical algorithm  for finding a point that would lie exactly on a line segment with corrections for floating point precision issues.

This is one of the tests I tried.  Unfortunately, the vertex s it generates has the exact same coordinates as the vertex c, and thus neither of them lies exactly on line a,b..  Vertex s should lie on a,b... but numeric issues result is a small error.
 
[Refine.txt](https://github.com/gwlucastrig/Tinfour/files/1814750/Refine.txt)

**Comment by gwlucastrig** [comment] 2018-03-17 21:03
I am going to close this issue in the near future.  I believe that the Tinfour code is working properly, even if the results are not quite what we would wish to see.

If the nearly degenerate triangles are truly a problem for your application, they can be removed  using the code that I have attached.  Unfortunately, this procedure disturbs the integrity of the mesh and not all of the Tinfour functions will work correctly afterward.  The attached code searches for nearly degenerate triangles on the perimeter and removes them (nearly degenerate triangles do not occur in the interior of the the TIN, only adjacent to the perimeter).  By "nearly degenerate" I mean "skinny triangles", those that have a very small positive-value for their computed area.

Once the triangle is removed, the perimeter will no longer be a convex polygon.  There will be a concavity at the site where the removal occurred. You will no longer be able to safely insert or remove vertices or constraints to or from the TIN (since the Delaunay criterion won't be guaranteed in the vicinity of the removal).  Sometimes add/remove will work. Sometimes they won't.  I think that the Lawson's walk algorithms will still work, though I do need to review its behavior in the exterior areas.  The getPerimeter() method and getEdges() methods will still work.  The Tinfour interpolation routines should still work (though I need to do more testing with the Natural Neighbors).

The main problem with this code is that it needs to be specific to the relevant IQuadEdge implementing classes. The IQuadEdge interface does not define edge-linking routines (setFoward, setReverse).  Only the specification implementations (QuadEdge and SemiVirtualEdge) implement these functions.  The example code I attached works on QuadEdge. You will note that IQuadEdge instance from getPerimeter() is specifically cast to a QuadEdge. A version to work on SemiVirtualEdge would have to do the same thing.  The reason that the IQuadEdge interface does not include these linking functions was that there was a performance issues when casting references from the interface type to a specific type (i.e. when performing a Java "narrow cast" operation). 


[TestCodeForPerimeterAdjustment.txt](https://github.com/gwlucastrig/Tinfour/files/1822077/TestCodeForPerimeterAdjustment.txt)

**Comment by jandam** [comment] 2018-03-18 09:47
Thank you,

  you are right Tinfour implementation is correct. And degenerated triangles are valid result for tin. I think that this is not issue when adding vertices.
  I think that code for adding constraints is accepting collinear edges with < vTolerance. It select wrong edge. I want to modify code for selecting edge with minimal value not just first that satisfies < vTolerance. This can solve the problem. #35
  So this issue can be closed. Thank you so much for the analysis.
  I'm reading your documentation and code again an again. 
  I will use your code on Monday. 

Martin

17. 3. 2018 v 22:03, gwlucastrig <notifications@github.com>:

**Comment by gwlucastrig** [comment] 2018-03-20 20:00
Issue is now closed

**Closed by gwlucastrig** 2018-03-20 20:00 UTC
